baseURL = 'https://yearofluddism.net'
title = 'Year of Luddism'
theme = "hugo-bearcub"
copyright = "tante (CC BY-4.0)"
defaultContentLanguage = "en"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[author]
  name = "tante"

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    title = "Year of Luddism"
    languageName = "English"
    LanguageCode = "en-US"
    contentDir = "content.en"
    [languages.en.params]
      blogPath = "/blog" # Path to your blog section (used by RSS)
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
  [languages.de]
    title = "Das Jahr des Luddismus"
    languageName = "Deutsch"
    LanguageCode = "de-DE"
    contentDir = "content.de"
    [languages.de.params]
      blogPath = "/de/blog" # Path to your blog section (used by RSS)
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params]
  # The description of your website
  description = "The Year of Luddism"

  # The path to your favicon
  # favicon = "images/favicon.png"


  # These images will show up when services want to generate a preview of a link
  # to your site. Ignored if `generateSocialCard = true`. For more information
  # about previews, see https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph
  #images = ["/hugo-bearcub/images/share.webp"]

  # This title is used as the site_name on the Hugo's internal opengraph
  # structured data template
  title = "Year of Luddism"

  # Dates are displayed following the format below. For more information about
  # formatting, see https://gohugo.io/functions/format/
  dateFormat = "Mon, 02 Jan 2023"

  # If your blog is multilingual but you haven't translated a page, this theme
  # will create a disabled link. By setting `hideUntranslated` to true, you can
  # have the theme simply not show any link
  hideUntranslated = false

  # (EXPERIMENTAL) This theme is capable of dynamically generating social cards
  # for posts that don't have `images` defined in their front matter; By setting
  # `generateSocialCard` to false, you can prevent this behavior. For more
  # information see layouts/partials/seo_tags.html
  generateSocialCard = true

  # Social media. Delete any item you aren't using to make sure it won't show up
  # in your website's metadata.
  [social]
    email = "tante@tante.cc" # Added to the navbar so readers can reply to posts
    twitter = "tante" # Twitter handle (without '@')
